galaxy_info:
  author: Timofey Biryukov
  description: Install Nginx whith TLS
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - 20.4
    - name: Debian
      versions:
        - 11
    - name: CentoOS
      versions:
        - 7
    - name: CentoOS Stream
      versions:
        - 8

  galaxy_tags: [nginx, tls]

dependencies: []

