nginx_ver: present
extra_packages: []
use_tls: false
use_php: true

# Nginx settings
worker_processes: auto
worker_connections: 1024
client_max_body_size: 32M

fastcgi_pass_path: 127.0.0.1:9000
# fastcgi_pass_path: unix:/run/php-fpm/www.sock

extra_packages:
  - letsencrypt
